kind: pipeline
name: default

steps:
- name: docker-tag-build
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: jerheij/proxy
    no_cache: true
    tags: ${DRONE_TAG}
  when:
    event:
      - tag

- name: docker-latest-build
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: jerheij/proxy
    no_cache: true
    tags: latest
  when:
    event:
      - push
    branch:
      - master

  notify:
    image: drillster/drone-email
    host: 192.168.169.3
    port: 25
    from: EMAIL_FROM
    recipients: [EMAIL_TO]
    recipients_only: true
    when:
      status: [success, failure]
